
#
host: localhost
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: birl_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: birl_test

production:
  adapter: postgresql
  prepared_statements: false
